//__RESET ROM 0000000000000000 00000001   R . . . . . .
;
; +-------------------------------------------------------------------------+
; |   This file has been generated by The Interactive Disassembler (IDA)    |
; |           Copyright (c) 2014 Hex-Rays, <support@hex-rays.com>           |
; |                      License info: 48-3057-7374-2C                      |
; |     Zhou Tao, Jiangsu Australia Sinuo Network Technology Co., Ltd.      |
; +-------------------------------------------------------------------------+
;
; Input MD5   : DE109DBB50E700D1573162AAEBD5FAF8
; Input CRC32 : F0EDC5B6

; File Name   : C:\011321\81102_my_final.bin
; Format      : Binary file
; Base Address: 0000h Range: 0000h - 0080h Loaded length: 00000080h
; Processor       : AVR [AT90S2313]
; Target assembler: AVR Assembler
; Segment type: Pure code
.CSEG ; ROM
.org 0

//UART_UDRE ROM 0000000000000008 00000001   R . . . . . .
.org 8
; UART Data Register Empty
; public UART_UDRE
UART_UDRE:
add     r13, r20
; End of function UART_UDRE

//UART_TX ROM 0000000000000009 00000002   R . . . . . .
.org 9
; UART, TX Complete
; public UART_TX
UART_TX:
call    0x15788C
; End of function UART_TX

//UART_RX ROM 0000000000000007 00000001   R . . . . . .
.org 7
; UART, RX Complete
; public UART_RX
UART_RX:
sbci    r16, -0x20 ; 'р'
; End of function UART_RX

//TIMER1_OVF1 ROM 0000000000000005 00000001   R . . . . . .
.org 5
; Timer/Counter1 Overflow
; public TIMER1_OVF1
TIMER1_OVF1:
cpse    r2, r5
; End of function TIMER1_OVF1

//TIMER1_COMP1 ROM 0000000000000004 00000001   R . . . . . .
.org 4
; Timer/Counter1 Compare Match
; public TIMER1_COMP1
TIMER1_COMP1:
subi    r17, 0x30 ; '0'
; End of function TIMER1_COMP1

//TIMER0_OVF0 ROM 0000000000000006 00000001   R . . . . . .
.org 6
; Timer/Counter0 Overflow
; public TIMER0_OVF0
TIMER0_OVF0:
sbc     r17, r1
; End of function TIMER0_OVF0

//INT1_ ROM 0000000000000002 00000001   R . . . . . .
.org 2
; External Interrupt Request 1
; public INT1_
INT1_:
ori     r17, 0xC8
; End of function INT1_